
name: Check pull request format
on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  check:
    name: Check PR
    runs-on: ubuntu-latest

    steps:
      - run: echo  "The job was automatically triggered in testbed."
      - name: Execute action
        uses: GuiBL4/github-actions/check-pull-request-action@check-pull-request-format-action-test
        with:
          pull-request-number: "${{ github.event.pull_request.number }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          pull-request-label: "${{contains(github.event.*.labels.*.name}}"
