
name: Check pull request format
on:
  pull_request_target:
    types: [opened]

jobs:
  check-pull-request:
    name: Check PR
    runs-on: ubuntu-latest

    steps:
      - name: Execute action
        uses: @SofairOfficial/github-actions/check-pull-request-action
        with:
          pull-request-number: "${{ github.event.pull_request.number }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
