
name: Check pull request format
on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  check:
    name: Check PR
    runs-on: ubuntu-latest

    steps:
      - name: Execute action
        uses: binadamu-isiyoonekana/github-actions/check-pull-request-action@check-wellformed-pull-request-action
        with:
          pull-request-number: "${{ github.event.pull_request.number }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
